### ISSUE TITLE
Failed logon does not give error.

### ISSUE THREAD

**Issue by Morindhal** [mattnenterprise/rust-pop3#17]
A failed logon to a "Microsoft Exchange POP3" server does not give a error, and sets the authenticated flag.

Wireshark summary:
S: -ERR Logon failure: unknown user name or bad password.

**Comment by jeprojects** [comment]
Fixed: https://github.com/mattnenterprise/rust-pop3/pull/19

**Comment by mattnenterprise** [comment]
This should have been fixed in bf607bbc8a2c472c075dc8086464b6ae5efed8e9
